[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "indicator-system-modelling"
version = "0.1.0"
requires-python = ">=3.12,<3.13"

dependencies = [
    "fastapi[standard]",
    "uvicorn[standard]",
    "numpy",
    "scipy",
]

[project.scripts]
run-indicator = "run_indicator_app:main"

[tool.setuptools]
py-modules = ["run_indicator_app"]

[tool.setuptools.packages.find]
where = ["."]

[tool.fastapi]
entrypoint = "fast_api.app_indicator.main:app"